version: "3.2"

services:
  svcbraum:
    build:
      context: .
      dockerfile: Dockerfile
    image: svc-braum
    env_file: .env
    ports:
      - 8002:8002
    volumes:
      - .:/usr/app
      - ./node_modules:/usr/app/node_modules
    depends_on:
      - redis
      - db
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - "braum-db:/var/lib/postgresql/data"
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"

volumes:
  braum-db:
